vich_uploader:
    db_driver: orm

    mappings:
        support_image:
            uri_prefix: /images/supports
            upload_destination: '%kernel.project_dir%/public/images/supports'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
